from notebook import Note, Notebook

if __name__ == "__main__":
    n1 = Note("hello first")
    n2 = Note("hello again")
    print(n1.id)
    print(n2.id)
    n1.match('hello')
    n = Notebook()
    print(dir(n))
    print(n.__dir__)
    print(n.__dict__)
    print(isinstance(n.modify_memo, object))
    print(isinstance(n.modify_memo, Note))
    print(isinstance(n.modify_memo, Notebook))
    print(isinstance(n1.match, object))
    print(isinstance(n1, object))

    n.new_note("hello world")
    print(n.notes[0])
    print(n.notes[0].id)
    print(dir(n))
    print(n.__dict__)
    n.new_note("hello again")
    print(isinstance(n.new_note, object))
    print(isinstance(n.__dict__, object))
    print(isinstance(n.notes[0].id, object))

    print(n.__dict__)
    print(n.notes[0].memo)
    print(n.notes[1].memo)
    n.modify_memo(1, "hi world")
    print(isinstance(n.notes[0].memo, object))
    print(n.search("hello"))
    print(n.search("world"))
    print(dir(n))